html: Work around Clang 20 + libstdc++13 issue w/ std::bind_front
It seems like _Bind_front_t isn't convertible to std::function with this
combination of compiler and stdlib.

```
./html/parser.h:36:11: error:
    no matching constructor for initialization of 'html2::Tokenizer'
./html2/tokenizer.h:258:5: note:
    candidate constructor not viable: no known conversion from
    '_Bind_front_t<void (Parser::*)(Tokenizer &, Token &&), Parser *>'
    to 'std::function<void (Tokenizer &, Token &&)>' for 2nd argument
```